# Data Science Day 9

## Introduction to NumPy

- NumPy is a Python package which stands for "Numerical Python"
- It is the core library for scientific computing, which contains a powerful n-dimensional array object, provide tools for integrating C, C++, etc.
- It is also useful in linear algebra, random number capability, etc.
- NumPy array can also be used as an efficient multi-dimensional container for generic data
    - NumPy array is a powerful N-dimensional array object which is in the form of rows and columns
    - We can initialize NumPy arrays from nested Python lists and access its elements
- Datasets can come from a wide range of sources and a wide range of formats, including collections of documents, collections of images, collections of sound clips, collections of numerical measurement, or nearly anything else
- Despite this apparent heterogeneity, it will help us to think of all data fundamentally as arrays of numbers
- For example, images - particularly digital images - can be thought of as simply two-dimensional arrays of numbers representing pixel brightness across the area
- Sound clips can be thought of as one-dimensional arrays of intensity versus time
- Text can be converted in various ways into numerical representations, perhaps binary digits representing the frequency of certain words or pairs of words
- No matter what the data are, the first step in making it analyzable will be to transform them into arrays of numbers
- For this reason, efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science
- NumPy provides an efficient interface to store and operate on dense data buffers
- In some ways, NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size
- NumPy arrays from the core of nearly the entire ecosystem of data science tools in Python

### Using NumPy

In [2]:
import numpy
numpy.__version__

'1.18.5'

In [3]:
import numpy as np

In [4]:
np? #documentation for NumPy

In [ ]:
np.<TAB> #display all the contents of the NumPy namespace

### NumPy Basics

- NumPy's main object is the homogeneous multidimensional array
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integrs
- In NumPy, dimensions are called axes
- NumPy's array class is called ndarray
    - It is also known by the alias array
- Noe that numpy.array is not the same as the class array.array, which only handles one-dimensional arrays and offers less functionality

In [ ]:
ndarray.ndim #the number of axes (dimension) of the array
ndarray.shape #the dimension of the array
ndarray.size #the total number of elements of the array
ndarray.dtype #the type of elements in the array
ndarray.itemsize #the size in bytes of each element of the array
ndarray.data #the actual elements of the array

In [9]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
a.shape

(3, 5)

In [11]:
a.ndim

2

In [12]:
a.dtype.name

'int64'

In [13]:
a.itemsize

8

In [14]:
a.size

15

In [15]:
type(a)

numpy.ndarray

In [16]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [17]:
type(b)

numpy.ndarray

In [18]:
b.size

3

In [19]:
b.shape

(3,)

### Array Creation

- There are several ways to create arrays
- For example, you can create an array from a regular Python list or tuple using the array function
- The type of the resulting array is deduced from the type of the elements in the sequences

In [20]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [21]:
a.dtype

dtype('int64')

In [22]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

- A frequent error consists in calling array with multiple arguments, rather than providing a single sequence as an argument

In [23]:
a = np.array(1,2,3,4) #WRONG

ValueError: only 2 non-keyword arguments accepted

In [24]:
a = np.array([1,2,3,4]) #RIGHT

- array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on

In [27]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

- The type of the array can also be explicitly specified at creation time:

In [28]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

- Often, the elements of an array are originally unknown, but its size is known
- NumPy offers several functions to create arrays with initial placeholder content
- These minimize the necessity of growing arrays, an expensive operation
- The function zeros creates an array full of zeroes, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory
- By default, the dtype of the created array is float64

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones( (2,3,4), dtype=np.int16 ) #dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [32]:
np.empty( (2,3) ) #uninitialized

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

- To create sequences of numbers, NumPy provides the arange function which is analogoues to the Python built-in range, but returns an array

In [34]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [35]:
np.arange( 0, 2, 0.3 ) #it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

- When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision
- For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [36]:
from numpy import pi
np.linspace( 0, 2, 9) #9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [37]:
x = np.linspace( 0, 2*pi, 100) #useful to evaluate function at lots of points
f = np.sin(x)

### Printing Arrays

- When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
    - The last axis is printed from left to right,
    - The second-to-last is printed from top to bottom,
    - The rest are also printed from top to bottom, with each slice separated from the next by an empty line
- One-dimensional arrays are then printed as rows, bidimensional as matrices, and tridimensionals as lists of matrices

In [38]:
a = np.arange(6) #1d array
print(a)

[0 1 2 3 4 5]


In [39]:
b = np.arange(12).reshape(4,3) #2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
c = np.arange(24).reshape(2,3,4) #3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


- If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [41]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [42]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


- To disable the behavior and force NumPy to print the entire array, you can change the printing options using set_printoptions

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)

### Basic Operations

- Arithmetic operators on arrays apply elementwise
- A new array is created and filled with the result

In [43]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [44]:
c = a-b
c

array([20, 29, 38, 47])

In [45]:
b**2

array([0, 1, 4, 9])

In [46]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [47]:
a<35

array([ True,  True, False, False])

- Unlike in many matrix languages, the product operator \* operates elementwise in NumPy arrays
- The matrix product can be performed using the @ operator (in python >= 3.5) or the dot function or meethod:

In [48]:
A = np.array( [[1,1],
              [0,1]] )
B = np.array( [[2,0],
              [3,4]] )
A * B #elementwise product

array([[2, 0],
       [0, 4]])

- Matrix multiplication is an operation that takes two matrices as input and produces a single matrix by multiplying rows of the first matrix to the column of the second matrix
- In matrix multiplication, make sure that the number of rows of the first matrix should be equal to the number of columns of the second matrix

In [49]:
A @ B #matrix product

array([[5, 4],
       [3, 4]])

In [50]:
A.dot(B) #another matrix product

array([[5, 4],
       [3, 4]])

- Some operations, such as += and \*=, act in place to modify an existing array rather than create a new one

In [51]:
rg = np.random.default_rng(1) #create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [52]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [53]:
a += b #b is not automatically converted to integer type

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

- When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting)

In [54]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [55]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [56]:
c.dtype.name

'float64'

In [58]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [59]:
d.dtype.name

'complex128'

- Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class

#### What does unary operation mean?

- In mathematics, a unary operation is an operation with only one operand, i.e., a single input
- This is in contrast to binary operations, which use two operands
- An example is the function f: A -> A, where A is a set
- The function f is a unary operation on A

In [60]:
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [61]:
a.sum()

3.1057109529998157

In [62]:
a.min()

0.027559113243068367

In [63]:
a.max()

0.8277025938204418

- By default, these operation apply to the array as though it were a list of numbers, regardless of its shape
- However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [64]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
b.sum(axis=0) #sum of each column

array([12, 15, 18, 21])

In [66]:
b.min(axis=1) #min of each row

array([0, 4, 8])

In [67]:
b.cumsum(axis=1) #cumulative sum of each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### Universal Functions

- NumPy provides familiar mathematical functions such as sin, cos, and exp
- In NumPy, these are called "universal functions" (ufunc)
- Within NumPy, these functions operate elementwise on an array, producing an array as output

In [68]:
B = np.arange(3)
B

array([0, 1, 2])

In [69]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [70]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [71]:
C = np.array([2., -1., 4.])

In [72]:
np.add(B, C)

array([2., 0., 6.])

### Indexing, Slicing, Iterating

- One-dimensional arrays can be indexed, sliced, and iterated over, much like lists and other Python sequences

In [73]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [74]:
a[2]

8

In [75]:
a[2:5]

array([ 8, 27, 64])

In [76]:
#equivalent to a[0:6:2] = 1000;
#from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [77]:
a[ : :-1] #reverse a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [78]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


- Multidimensional arrays can have one index per axis
- These indices are given in a tuple separated by commas:

In [79]:
def f(x,y):
    return 10*x+y

In [80]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [81]:
b[2,3]

23

In [82]:
b[0:5, 1] #each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [83]:
b[ : ,1] #equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [84]:
b[1:3, :] #each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

- When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [85]:
b[-1] #the last row, equivalent to b[-1,:]

array([40, 41, 42, 43])

- The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes
- NumPy also allows you to write this using dots as b[i,...]
- The dots (...) represent as many colons as needed to produce a complete indexing tuple
- For example, if x is an array with 5 axes, then
    - x[1,2,...] is equivalent to x[1,2,:,:,:]
- NumPy arrays have an attribute called shape that returns a tuple with eachindex having the number of corresponding elements

In [86]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [90]:
c = np.array( [[[ 0, 1, 2], #a 3d array (two stakced 2d arrays)
               [ 10, 12, 13]],
               [[100,101,102],
               [110,112,113]]])

In [91]:
c.shape

(2, 2, 3)

In [92]:
c[1,...] #same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [93]:
c[...,2]

array([[  2,  13],
       [102, 113]])

- Iterating over multidimensional arrays is done with respect to the first axis:

In [94]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [95]:
for row in c:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


- However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [96]:
for element in b.flat:
    print(element)
    #print(element*2)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### Shape Manipulation

#### Changing the shape of an array

#### What is the shape of an array?

- Shape is a tuple that gives you an indication of the number of dimensions in the array
- An array has a shape given by the number of elements along each axis:

In [97]:
a = np.floor(10*rg.random((3,4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [98]:
a.shape

(3, 4)

- The shape of an array can be changed with various commands
- Note that the following three commands all return a modified array, but do not change the original array:

In [99]:
a.ravel() #returns the array, flattened

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [100]:
a.reshape(6,2) #returns the array with a modified shape

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [101]:
a.T #returns the array, transposed

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [102]:
a.T.shape

(4, 3)

In [103]:
a.shape

(3, 4)

- The order of the elements in the array resulting from ravel() is that the rightmost index changes the fastest, so the element after a[0,0] is a[0,1]
- The reshape function returns its argument with a modified shape, where the ndarray.resize method modifies the array itself:

In [104]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [105]:
a.resize((2,6))

In [106]:
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [107]:
a.reshape(3,-1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

- Several arrays can be stacked together along different axes:

In [108]:
a = np.floor(10*rg.random((2,2)))
a

array([[9., 7.],
       [5., 2.]])

In [109]:
b = np.floor(10*rg.random((2,2)))
b

array([[1., 9.],
       [5., 1.]])

In [110]:
np.vstack((a,b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [111]:
np.hstack((a,b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

- The function column_stack stacks 1D arrays as columns into a 2D array
- It is equivalent to hstack only for 2D arrays:

In [112]:
from numpy import newaxis
np.column_stack((a,b)) #with 2D arrays

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [113]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b)) #returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [114]:
np.hstack((a,b)) #the result is different

array([4., 2., 3., 8.])

In [115]:
a[:,newaxis] #view a as a 2D column vector

array([[4.],
       [2.]])

In [116]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [117]:
np.hstack((a[:,newaxis],b[:,newaxis])) #the result is the same

array([[4., 3.],
       [2., 8.]])

- On the other hand, the function row_stack is equivalent to vstack for any input arrays; in fact, tow_stack is an alis for vstack:

In [118]:
np.column_stack is np.hstack

False

In [119]:
np.row_stack is np.vstack

True

- In general, for arrays with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional argument giving the number of the axis along which the concatenation should happen
- In complex cases, r and c are useful for creating arrays by stacking numbers along one axis
- They allow the use of range literals (":")

In [120]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

### Splitting One Array Into Several Small Ones

- Using hsplit, you can split an array long its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [121]:
a = np.floor(10*rg.random((2,12)))
a

array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

In [122]:
np.hsplit(a,3)

[array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]]),
 array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]),
 array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]])]

#### Copies and Views

- When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not
- No Copy At All
    - Simple assignments make no copy of objects or their data:

In [124]:
a = np.array([[ 0, 1, 2, 3],
             [ 4, 5, 6, 7],
             [ 8, 9, 10, 11]])
b = a
b is a

True

- View Or Shallow Copy
    - Different array objects can share the same data
    - The view method creates a new array object that looks at the same data

In [126]:
c = a.view()
c is a

False

In [127]:
c.base is a #c is a view of the data owned by a

True

In [128]:
c.flags.owndata

False

In [129]:
c = c.reshape((2, 6)) #a's shape doesn't change
a.shape

(3, 4)

In [130]:
c[0, 4] = 1234 #a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

- Slicing an array returns a view of it:

In [131]:
s = a[ :, 1:3] #spaces added for clarity; could also be written s = a[:, 1:3]
s[:] = 10 #s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

- Deep Copy
    - The copy method makes a complete copy of the array and its data

In [132]:
d = a.copy() #a new array object with new data is created
d is a

False

In [133]:
d.base is a #d doesn't share anything with a

False

In [134]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

- Sometimes copy should be called after slicing if the original array is not required anymore
- For example, suppose a is a huge intermediate result and the final result b only contains a small fraction of a, a deep copy should be made when constructing b with slicing:

In [135]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a #the memory of a can be released